[
	{
		'file': 'test/sources/simple.fey',
		'symbols': [
			LexToken('DIRECTIVEOPEN_ACTION','[',1,0),
			LexToken('ID','Bob',1,1),
			LexToken(':',':',1,4),
			LexToken('ID','pissed',1,6),
			LexToken(']',']',1,12),
			LexToken('DIRECTIVEOPEN_ACTION','[',2,14),
			LexToken('ID','Bob',2,15),
			LexToken(':',':',2,18),
			LexToken('GO','GO',2,20),
			LexToken('TO','TO',2,23),
			LexToken('ID','stage-front',2,26),
			LexToken(']',']',2,37),
			LexToken('DIRECTIVEOPEN_ACTION','[',3,39),
			LexToken('ID','Bob',3,40),
			LexToken(':',':',3,43),
			LexToken('GO','GO',3,45),
			LexToken('TO','TO',3,48),
			LexToken('ID','stage-left',3,51),
			LexToken('QUICKLY','QUICKLY',3,62),
			LexToken(']',']',3,69),
			LexToken('DIRECTIVEOPEN_ACTION','[',4,71),
			LexToken('ID','Bob',4,72),
			LexToken(':',':',4,75),
			LexToken('ID','pissed',4,77),
			LexToken(',',',',4,83),
			LexToken('ID','happy',4,85),
			LexToken(',',',',4,90),
			LexToken('GO','GO',4,92),
			LexToken('TO','TO',4,95),
			LexToken('ID','bookshelf',4,98),
			LexToken('SLOWLY','SLOWLY',4,108),
			LexToken(']',']',4,114)
		]
	}
]
